### PR TITLE
Add h/b/k flag - "lesser speed hacks", free rainbow bridge, no magic key requirements

### PR DESCRIPTION
**Pull request by gameboy9**
I added an "h" (lower case) flag for those who don't like the speedy text but enjoy the rest of the speed hacks, can enjoy just that.

I also added a way to build the rainbow bridge for free.  (optional of course; b flag)

Now I've added a way to open all doors without a magic key.  But I wasn't able to substitute the keys in the chests with 500+ gold.  I commented what I tried so you can take a look at it.

### CODE REVIEW

**Comment by mcgrew** [comment]
It looks like you added a couple of extraneous files. Also there are some significant changes I haven't pushed up yet that will require this to be merged manually I imagine.

On the bright side I cleaned up the GUI code - it is much easier to modify now.

**Comment by mcgrew** [comment]
On the lesser speed hacks front, I feel like it'll be a good idea to just separate fast text from the rest and make them separate options. I can implement that.

**Comment by mcgrew** [comment]
Also FYI, I had already implemented the free bridge (oops) and shortened Charlock (small bug to fix there still, which is why I haven't pushed)

**Comment by gameboy9** [comment]
It's possible that I may have added a .sln file (Visual Studio); I've been using Visual Studio to sync to GitHub.

**Comment by mcgrew** [comment]
There's a VSWorkspaceState.json, dwrandomizer.pro.user, and an slnx.sqlite file.

**Comment by gameboy9** [comment]
Ohhhh... that might be QT related in fact...

**Comment by mcgrew** [comment]
Don't sorry about it, I'll sort it out when I get the chance to merge it.

**Comment by mcgrew** [comment]
I might end up closing this since I already had most of it implemented before I saw this and there were a lot of conflicts. I added the "no key" stuff just now. In the future I'll try to keep the github repo closer to what I have locally.

**Comment by gameboy9** [comment]
Ah OK, that's cool.  Feel free to close.

**Pull request closed without merging**
