### PR TITLE
Numerous proposed features

### PR DESCRIPTION
**Pull request by gameboy9**
- Fixed a bug where the minimum was twice the intended minimum.  This
increased the maximum as well.
- Altered stat logic as follows:
Strength from 8-155 (was 4-155)
Agility from 4-155 (was 4-145)
HP from 15-230, 25-230 if Tantegel is in a swamp.  (10-230)
All of the above have slightly slower power curves.
This should make it easier to get out of level 1, but endgame grinding
should still exist.

### CODE REVIEW

**Comment by gameboy9** [comment]
I reverted the stats to the old 1.3 values and added a "no equipment" option.

**Comment by gameboy9** [comment]
Added a no equipment option, a random% option, and options to change stat growths.

I also successfully expanded the ROM.  However, no functionality is changed with this development, but it definitely blows the door wide open for things such as game statistics.

**Comment by Kronoan** [comment]
Cool!

**Comment by gameboy9** [comment]
[stats.zip](https://github.com/mcgrew/dwrandomizer/files/1596328/stats.zip)

Attached is a LUA file which outputs all of the stats I've added to the pull request.

**Pull request closed without merging**
